version: '3.7'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: 'prac_compose_nginx'
    ports: 
      - 8080:80
    volumes: 
      - ./web/src:/usr/share/nginx/html
